### PR TITLE
feat: [sc-24375] Add unicode version for each character

### PR DESCRIPTION
**Pull request by Carbon225**

### CODE REVIEW

**Comment by lightwalker-eth** [comment]
@Carbon225 Hey overall this PR looks great. Just a few actions items before we close this:

1. Ideally we would fix the tests that are failing or being cancelled. I've added some suggestions in this Slack thread: https://namehash.slack.com/archives/C03JQ5URTEG/p1721666686483419 Options include waiting for PR 286 is merged to main and then rebase this PR, etc..
2. We need to create a changeset as part of this PR because it makes a change to one of the packages we publish to NPM. Please see some instructions for this here: https://namehash.slack.com/archives/C03JQ5URTEG/p1721666686483419 If you follow the steps here, a small little file will get added to this PR identifying that there's been a minor update to the `nameguard-sdk` package with a short description of that change (ex: "Added `unicode_version` field to `ConsolidatedGraphemeGuardReport`."). Once you follow the steps that add this file to your PR, then you're all finished for the steps involved in this PR for changesets. We will then later use that little changeset file to help automate updates to packages we are publishing to NPM. If you have any questions on this please contact me, Jamie, or anyone else on the team very happy to help :+1:

**Review by lightwalker-eth — CHANGES_REQUESTED** [review]
Code looks good :+1: Please see requested action items here: https://github.com/namehash/namekit/pull/315#issuecomment-2245519786

**Review by lightwalker-eth — CHANGES_REQUESTED** [review]
@Carbon225 Hey good news: PR 286 is now merged! Can you please get this branch ready to merge with main and ensure all our tests / CI steps pass? Thank you!

**Review by djstrong — APPROVED** [review]

**Comment by djstrong** [comment]
@lightwalker-eth It is ready to merge.

**Review by lightwalker-eth — APPROVED** [review]
Looks good :+1:

**Pull request merged**
